## Numpy

In [14]:
import numpy as np

testarr=np.array([1,3,4,1],float) #only one data type
print(testarr)
print(type(testarr))
print(type(testarr[3]))

testlist=[1,3,4,'헛']
print(testlist)
print(type(testlist))
print(type(testlist[3]))


[1. 3. 4. 1.]
<class 'numpy.ndarray'>
<class 'numpy.float64'>
[1, 3, 4, '헛']
<class 'list'>
<class 'str'>


In [17]:
#ndarray에서 실수로 다른 data type 입력해도 -> 지정 type으로 자동 형변환
testarr=np.array([1,2,3,'6'],int)
testarr

array([1, 2, 3, 6])

### array Rank Name
```
scalar  7
vector  [7,7]
matrix  [[7,7],[8,8]]
3-tensor[[1,1,1],[2,1,2],[7,7,7],[2,2,2]]
```


In [20]:
vector=[1,2,3,4]
np.array(vector,int).shape

(4,)

In [21]:
matricx=[[1,2,3,4],[1,2,3,4],[1,2,3,4]]
np.array(matricx,int).shape

(3, 4)

In [27]:
tensor=[[[1,2,3,4],[1,2,3,4],[1,2,3,4]],
        [[1,2,3,4],[1,2,3,4],[1,2,3,4]]]
np.array(tensor,int).shape

(2, 3, 4)

```
ndarray, matrix, tensor를 코드에 적힌 그대로 직관적인 게 아닌
나름의 해석이 필요한 것
```

In [29]:
testarr=np.array([[1,2,3,'6'],[2,3,4,'7']],int)
testarr

array([[1, 2, 3, 6],
       [2, 3, 4, 7]])

### nbytes : ndarray 메모리 크기

In [37]:
test=np.array([[1,2,3],[4.5,'5','6']],float)
print(test)

[[1.  2.  3. ]
 [4.5 5.  6. ]]


In [39]:
test_b=np.array([[1,2,3],[4.5,'5','6']],float).nbytes
print(test_b)

48


In [41]:
print(np.array([[1,2,3],[4.5,'5','6']],float).nbytes)

48


In [44]:
print(np.array([[1,2,3],[4.5,'5','6']],dtype=np.float32).nbytes)

24


In [45]:
print(np.array([[1,2,3],[4.5,'5','6']],dtype=np.float64).nbytes)

48


In [47]:
print(np.array([[1,2,3],[4.5,'5','6']],dtype=np.int8).nbytes)

6


In [48]:
print(np.array([[1,2,3],[4.5,'5','6']],dtype=np.string).nbytes) #숫자만가능 

AttributeError: module 'numpy' has no attribute 'string'

In [49]:
print(np.array([[1,2,3],[4.5,'5','6']],dtype=np.int16).nbytes)

12


### reshape

```
array의 shape 변경
```

In [51]:
test=[[1,2,3,4],[1,2,3,4]]
print(type(test))

<class 'list'>


In [55]:
test=np.array(test)
print(type(test))
test.shape

<class 'numpy.ndarray'>


(2, 4)

In [56]:
test.reshape(8,)

array([1, 2, 3, 4, 1, 2, 3, 4])

In [57]:
test.reshape(8,).shape

(8,)

In [58]:
test=[[1,2,3,4],[1,2,3,4]]
np.array(test).reshape(8,)

array([1, 2, 3, 4, 1, 2, 3, 4])

### flatten
```
다차원 array를 1차원으로
```

In [60]:
test=[[1,2,3,4],[1,2,3,4]]
test=np.array(test)
test.flatten()

array([1, 2, 3, 4, 1, 2, 3, 4])

In [63]:
test=[[1,2,3,4],[1,2,3,4]]
np.array(test).flatten()

array([1, 2, 3, 4, 1, 2, 3, 4])

### indexing for Numpy

In [75]:
test=np.array([[1,2,3,4],[1,2,3,4.5]],int)
test[0,0]=67
print(test)

[[67  2  3  4]
 [ 1  2  3  4]]


In [76]:
test[0][0]

67

In [77]:
test[0,0]

67

### slicing for numpy array

In [78]:
a=np.array([[1,2,3,4],[1,2,3,4.5]],int)
a

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [79]:
a[:,2:]

array([[3, 4],
       [3, 4]])

In [80]:
a

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [83]:
a[1,1:3]

array([2, 3])

In [95]:
a[1:3]

array([[1, 2, 3, 4]])

In [84]:
a

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [87]:
a[1:3,:]

array([[1, 2, 3, 4]])

In [97]:
a[1:3,]

array([[1, 2, 3, 4]])

-----------------------------------------------numpy 38,39,41,42,43,44,46,47,48,49,51,52,54,57,62,64 

In [101]:
%timeit np.array([[1,2,3,4],[1,2,3,4.5]],int)

896 ns ± 6.22 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [102]:
%timeit test=[[1,2,3,4],[1,2,3,4]]

100 ns ± 0.906 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


#### fancy index
79,80,82